; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "翻金币游戏"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "My company, Inc."
!define PRODUCT_WEB_SITE "http://www.mycompany.com"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\CoinFlip.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "Coin\coin.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "许可协议.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\CoinFlip.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\翻金币游戏"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR\audio"
  SetOverwrite try
  File "Coin\audio\qtaudio_windows.dll"
  SetOutPath "$INSTDIR\bearer"
  File "Coin\bearer\qgenericbearer.dll"
  SetOutPath "$INSTDIR"
  File "Coin\coin.ico"
  File "Coin\CoinFlip.exe"
  CreateDirectory "$SMPROGRAMS\翻金币游戏"
  CreateShortCut "$SMPROGRAMS\翻金币游戏\翻金币游戏.lnk" "$INSTDIR\CoinFlip.exe"
  CreateShortCut "$DESKTOP\翻金币游戏.lnk" "$INSTDIR\CoinFlip.exe" "" "$INSTDIR\coin.ico"
  File "Coin\D3Dcompiler_47.dll"
  SetOutPath "$INSTDIR\iconengines"
  File "Coin\iconengines\qsvgicon.dll"
  SetOutPath "$INSTDIR\imageformats"
  File "Coin\imageformats\qgif.dll"
  File "Coin\imageformats\qicns.dll"
  File "Coin\imageformats\qico.dll"
  File "Coin\imageformats\qjpeg.dll"
  File "Coin\imageformats\qsvg.dll"
  File "Coin\imageformats\qtga.dll"
  File "Coin\imageformats\qtiff.dll"
  File "Coin\imageformats\qwbmp.dll"
  File "Coin\imageformats\qwebp.dll"
  SetOutPath "$INSTDIR"
  File "Coin\libEGL.dll"
  File "Coin\libgcc_s_dw2-1.dll"
  File "Coin\libGLESV2.dll"
  File "Coin\libstdc++-6.dll"
  File "Coin\libwinpthread-1.dll"
  SetOutPath "$INSTDIR\mediaservice"
  File "Coin\mediaservice\dsengine.dll"
  File "Coin\mediaservice\qtmedia_audioengine.dll"
  SetOutPath "$INSTDIR"
  File "Coin\opengl32sw.dll"
  SetOutPath "$INSTDIR\platforms"
  File "Coin\platforms\qwindows.dll"
  SetOutPath "$INSTDIR\playlistformats"
  File "Coin\playlistformats\qtmultimedia_m3u.dll"
  SetOutPath "$INSTDIR"
  File "Coin\Qt5Core.dll"
  File "Coin\Qt5Gui.dll"
  File "Coin\Qt5Multimedia.dll"
  File "Coin\Qt5Network.dll"
  File "Coin\Qt5Svg.dll"
  File "Coin\Qt5Widgets.dll"
  SetOutPath "$INSTDIR\styles"
  File "Coin\styles\qwindowsvistastyle.dll"
  SetOutPath "$INSTDIR\translations"
  File "Coin\translations\qt_ar.qm"
  File "Coin\translations\qt_bg.qm"
  File "Coin\translations\qt_ca.qm"
  File "Coin\translations\qt_cs.qm"
  File "Coin\translations\qt_da.qm"
  File "Coin\translations\qt_de.qm"
  File "Coin\translations\qt_en.qm"
  File "Coin\translations\qt_es.qm"
  File "Coin\translations\qt_fi.qm"
  File "Coin\translations\qt_fr.qm"
  File "Coin\translations\qt_gd.qm"
  File "Coin\translations\qt_he.qm"
  File "Coin\translations\qt_hu.qm"
  File "Coin\translations\qt_it.qm"
  File "Coin\translations\qt_ja.qm"
  File "Coin\translations\qt_ko.qm"
  File "Coin\translations\qt_lv.qm"
  File "Coin\translations\qt_pl.qm"
  File "Coin\translations\qt_ru.qm"
  File "Coin\translations\qt_sk.qm"
  File "Coin\translations\qt_uk.qm"
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\翻金币游戏\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\翻金币游戏\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\CoinFlip.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\CoinFlip.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\translations\qt_uk.qm"
  Delete "$INSTDIR\translations\qt_sk.qm"
  Delete "$INSTDIR\translations\qt_ru.qm"
  Delete "$INSTDIR\translations\qt_pl.qm"
  Delete "$INSTDIR\translations\qt_lv.qm"
  Delete "$INSTDIR\translations\qt_ko.qm"
  Delete "$INSTDIR\translations\qt_ja.qm"
  Delete "$INSTDIR\translations\qt_it.qm"
  Delete "$INSTDIR\translations\qt_hu.qm"
  Delete "$INSTDIR\translations\qt_he.qm"
  Delete "$INSTDIR\translations\qt_gd.qm"
  Delete "$INSTDIR\translations\qt_fr.qm"
  Delete "$INSTDIR\translations\qt_fi.qm"
  Delete "$INSTDIR\translations\qt_es.qm"
  Delete "$INSTDIR\translations\qt_en.qm"
  Delete "$INSTDIR\translations\qt_de.qm"
  Delete "$INSTDIR\translations\qt_da.qm"
  Delete "$INSTDIR\translations\qt_cs.qm"
  Delete "$INSTDIR\translations\qt_ca.qm"
  Delete "$INSTDIR\translations\qt_bg.qm"
  Delete "$INSTDIR\translations\qt_ar.qm"
  Delete "$INSTDIR\styles\qwindowsvistastyle.dll"
  Delete "$INSTDIR\Qt5Widgets.dll"
  Delete "$INSTDIR\Qt5Svg.dll"
  Delete "$INSTDIR\Qt5Network.dll"
  Delete "$INSTDIR\Qt5Multimedia.dll"
  Delete "$INSTDIR\Qt5Gui.dll"
  Delete "$INSTDIR\Qt5Core.dll"
  Delete "$INSTDIR\playlistformats\qtmultimedia_m3u.dll"
  Delete "$INSTDIR\platforms\qwindows.dll"
  Delete "$INSTDIR\opengl32sw.dll"
  Delete "$INSTDIR\mediaservice\qtmedia_audioengine.dll"
  Delete "$INSTDIR\mediaservice\dsengine.dll"
  Delete "$INSTDIR\libwinpthread-1.dll"
  Delete "$INSTDIR\libstdc++-6.dll"
  Delete "$INSTDIR\libGLESV2.dll"
  Delete "$INSTDIR\libgcc_s_dw2-1.dll"
  Delete "$INSTDIR\libEGL.dll"
  Delete "$INSTDIR\imageformats\qwebp.dll"
  Delete "$INSTDIR\imageformats\qwbmp.dll"
  Delete "$INSTDIR\imageformats\qtiff.dll"
  Delete "$INSTDIR\imageformats\qtga.dll"
  Delete "$INSTDIR\imageformats\qsvg.dll"
  Delete "$INSTDIR\imageformats\qjpeg.dll"
  Delete "$INSTDIR\imageformats\qico.dll"
  Delete "$INSTDIR\imageformats\qicns.dll"
  Delete "$INSTDIR\imageformats\qgif.dll"
  Delete "$INSTDIR\iconengines\qsvgicon.dll"
  Delete "$INSTDIR\D3Dcompiler_47.dll"
  Delete "$INSTDIR\CoinFlip.exe"
  Delete "$INSTDIR\coin.ico"
  Delete "$INSTDIR\bearer\qgenericbearer.dll"
  Delete "$INSTDIR\audio\qtaudio_windows.dll"

  Delete "$SMPROGRAMS\翻金币游戏\Uninstall.lnk"
  Delete "$SMPROGRAMS\翻金币游戏\Website.lnk"
  Delete "$DESKTOP\翻金币游戏.lnk"
  Delete "$SMPROGRAMS\翻金币游戏\翻金币游戏.lnk"

  RMDir "$SMPROGRAMS\翻金币游戏"
  RMDir "$INSTDIR\translations"
  RMDir "$INSTDIR\styles"
  RMDir "$INSTDIR\playlistformats"
  RMDir "$INSTDIR\platforms"
  RMDir "$INSTDIR\mediaservice"
  RMDir "$INSTDIR\imageformats"
  RMDir "$INSTDIR\iconengines"
  RMDir "$INSTDIR\bearer"
  RMDir "$INSTDIR\audio"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd